new ticketHandler
frixtaylor1/tp_final_ayed pull request #2
Opened 2023-11-01 00:29 UTC by mateoroca

2023-11-01 00:56 UTC, frixtaylor1 commented on src/Handlers/TicketHandler.hpp
> +  ~TicketHandler(){};
en el destructor deberías de recorrer toda la lista de tickets que fueron creados y eliminarlos de la memoria. ej:

`
for (auto ticket : this->tickets) {
    if (ticket) {
        delete ticket;    
    }
}
`

2023-11-01 00:57 UTC, frixtaylor1 commented on src/Handlers/TicketHandler.hpp
> +
eliminar espacio

2023-11-01 00:57 UTC, frixtaylor1 commented on src/Handlers/TicketHandler.hpp
> +
espacio

2023-11-01 00:58 UTC, frixtaylor1 commented on src/Handlers/TicketHandler.hpp
> +
eliminar linea sin código

2023-11-01 00:59 UTC, frixtaylor1 requested changes
Hace los cambios en el destructor que te comenté.
Luego estaría para mergear ya que lo demás son solo comentarios de espacios que quedaron adicionalmente...

2023-11-03 18:20 UTC, mateoroca commented on src/Handlers/TicketHandler.hpp
> +
ok

2023-11-03 18:20 UTC, merged